#!/bin/bash

PKG_NAME=securly
munkipkg --create $PKG_NAME-install
munkipkg --create $PKG_NAME-uninstall

INSTALL_DIR=$PKG_NAME-install
UNINSTALL_DIR=$PKG_NAME-uninstall
SCRIPTS_PATH=scripts/postinstall

cp securly $INSTALL_DIR/$SCRIPTS_PATH
cp securly-uninstall $UNINSTALL_DIR/$SCRIPTS_PATH
cd $INSTALL_DIR
sed -i ".bak" "s/com.github.munki/org.mirman/" build-info.plist
sed -i ".bak" "s/<string>1.0/<string>$(cat ../version)/" build-info.plist
sed -i ".bak" "s/\${version}/$(cat ../version)/" build-info.plist
munkipkg ./
cd $UNINSTALL_DIR
sed -i ".bak" "s/com.github.munki/org.mirman/" build-info.plist
sed -i ".bak" "s/<string>1.0/<string>$(cat ../version)/" build-info.plist
sed -i ".bak" "s/\${version}/$(cat ../version)/" build-info.plist
munkipkg ./
cd ..
exit 0