#!/bin/bash

servers="50.18.216.174 50.18.216.175"
networksetup -listallnetworkservices | sed 1d $file | while read adapter
do
    networksetup -setdnsservers "$adapter" $servers
    networksetup -setv6off "$adapter"
done
dscacheutil -flushcache
killall -HUP -mDNSResponder
exit 0
